# Generated by Django 4.1.7 on 2023-04-28 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerscount',
            old_name='followe',
            new_name='follower',
        ),
    ]
